name: bantam_parser
description: A Bantam parser for Dart.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
   source_span: 1.9.1
   charcode: 1.3.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
